# Form implementation generated from reading ui file 'ui/BookInfo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        self.title = QtWidgets.QLabel(parent=Form)
        self.title.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.title.setObjectName("title")
        self.title_label = QtWidgets.QLabel(parent=Form)
        self.title_label.setGeometry(QtCore.QRect(10, 40, 121, 51))
        self.title_label.setText("")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.author = QtWidgets.QLabel(parent=Form)
        self.author.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.author.setObjectName("author")
        self.author_label = QtWidgets.QLabel(parent=Form)
        self.author_label.setGeometry(QtCore.QRect(10, 120, 121, 51))
        self.author_label.setText("")
        self.author_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.author_label.setWordWrap(True)
        self.author_label.setObjectName("author_label")
        self.genre = QtWidgets.QLabel(parent=Form)
        self.genre.setGeometry(QtCore.QRect(10, 180, 121, 31))
        self.genre.setObjectName("genre")
        self.genre_label = QtWidgets.QLabel(parent=Form)
        self.genre_label.setGeometry(QtCore.QRect(10, 210, 121, 51))
        self.genre_label.setText("")
        self.genre_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.genre_label.setWordWrap(True)
        self.genre_label.setObjectName("genre_label")
        self.year = QtWidgets.QLabel(parent=Form)
        self.year.setGeometry(QtCore.QRect(10, 270, 131, 31))
        self.year.setObjectName("year")
        self.year_label = QtWidgets.QLabel(parent=Form)
        self.year_label.setGeometry(QtCore.QRect(10, 300, 121, 61))
        self.year_label.setText("")
        self.year_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.year_label.setWordWrap(True)
        self.year_label.setObjectName("year_label")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(200, 20, 320, 460))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Название</span></p></body></html>"))
        self.author.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Автор</span></p></body></html>"))
        self.genre.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Жанр</span></p></body></html>"))
        self.year.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Год создания</span></p></body></html>"))
